### ISSUE TITLE
In Module 1.0.2 it's now showing fronted side.

### ISSUE THREAD

**Issue by www-vivek55** [aymakan/magento2#1]
In Module 1.0.2. After enable. while order on frontend side. Aymakan shipping method not showing.

**Comment by altafhussain10** [comment]
Hello, 

Please check the module documentation https://github.com/aymakan/magento2 . 

Our module is not providing any frontend features. It only enables stores to create AWB and print them. 

Thanks

**Comment by www-vivek55** [comment]
You can check-in screenshot in here.

![image](https://user-images.githubusercontent.com/17611114/102462763-3b47ad00-4070-11eb-9b42-3319902ba2d2.png)

**Comment by altafhussain10** [comment]
Either the module is custmoized or the shipping method is added using flat method. But our module does not provide this feature.
